CREATE TABLE Measurements (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    [Timestamp] DATETIME2 NOT NULL,
    SensorId NVARCHAR(50) NOT NULL,
    Zona NVARCHAR(100) NOT NULL,
    Tipo NVARCHAR(50) NOT NULL,
    Valor FLOAT NOT NULL
);

CREATE TABLE VideoEvents (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    [Timestamp] DATETIME2 NOT NULL,
    SensorId NVARCHAR(50) NOT NULL,
    Zona NVARCHAR(100) NOT NULL,
    FileName NVARCHAR(260) NOT NULL,
    FilePath NVARCHAR(500) NOT NULL,
    FileSize BIGINT NOT NULL
);